array(1) {
  ["meals"] => array(1) {
    [0] => array(53) {
      ["idMeal"] => string(5) "52975"
      ["strMeal"] => string(18) "Tuna and Egg Briks"
      ["strDrinkAlternate"] => NULL["strCategory"] => string(7) "Seafood"
      ["strArea"] => string(8) "Tunisian"
      ["strInstructions"] => string(1533) "Heat 2 tsp of the oil in a large saucepan and cook the spring onions over a low heat for 3 minutes or until beginning to soften. Add the spinach, cover with a tight-fitting lid and cook for a further 2–3 minutes or until tender and wilted, stirring once or twice. Tip the mixture into a sieve or colander and leave to drain and cool. Using a saucer as a guide, cut out 24 rounds about 12.5 cm (5 in) in diameter from the filo pastry, cutting 6 rounds from each sheet. Stack the filo rounds in a pile, then cover with cling film to prevent them from drying out. When the spinach mixture is cool, squeeze out as much excess liquid as possible, then transfer to a bowl. Add the tuna, eggs, hot pepper sauce, and salt and pepper to taste. Mix well. Preheat the oven to 200°C (400°F, gas mark 6). Take one filo round and very lightly brush with some of the remaining oil. Top with a second round and brush with a little oil, then place a third round on top and brush with oil. Place a heaped tbsp of the filling in the middle of the round, then fold the pastry over to make a half-moon shape. Fold in the edges, twisting them to seal, and place on a non-stick baking sheet. Repeat with the remaining pastry and filling to make 8 briks in all. Lightly brush the briks with the remaining oil. Bake for 12–15 minutes or until the pastry is crisp and golden brown. Meanwhile, combine the tomatoes and cucumber in a bowl and sprinkle with the lemon juice and seasoning to taste. Serve the briks hot with this salad and the chutney."
      ["strMealThumb"] => string(65) "https://www.themealdb.com/images/media/meals/2dsltq1560461468.jpg"
      ["strTags"] => NULL["strYoutube"] => string(43) "https://www.youtube.com/watch?v=C5n1fN8TGHs"
      ["strIngredient1"] => string(9) "Olive Oil"
      ["strIngredient2"] => string(13) "Spring Onions"
      ["strIngredient3"] => string(7) "Spinach"
      ["strIngredient4"] => string(11) "Filo Pastry"
      ["strIngredient5"] => string(4) "Tuna" ["strIngredient6"] => string(4) "Eggs"
      ["strIngredient7"] => string(8) "Hotsauce"
      ["strIngredient8"] => string(8) "Tomatoes"
      ["strIngredient9"] => string(8) "Cucumber"
      ["strIngredient10"] => string(11) "Lemon Juice"
      ["strIngredient11"] => string(11) "Apricot Jam"
      ["strIngredient12"] => string(0) ""
      ["strIngredient13"] => string(0) ""
      ["strIngredient14"] => string(0) ""
      ["strIngredient15"] => string(0) ""
      ["strIngredient16"] => string(0) ""
      ["strIngredient17"] => string(0) ""
      ["strIngredient18"] => string(0) ""
      ["strIngredient19"] => string(0) ""
      ["strIngredient20"] => string(0) ""
      ["strMeasure1"] => string(5) "2 tbs"
      ["strMeasure2"] => string(1) "8"
      ["strMeasure3"] => string(4) "200g"
      ["strMeasure4"] => string(1) "4"
      ["strMeasure5"] => string(6) "1 can "
      ["strMeasure6"] => string(1) "2"
      ["strMeasure7"] => string(4) "Dash"
      ["strMeasure8"] => string(9) "4 Chopped"
      ["strMeasure9"] => string(4) "1/4 "
      ["strMeasure10"] => string(5) "1 tbs"
      ["strMeasure11"] => string(5) "4 tbs"
      ["strMeasure12"] => string(1) " "
      ["strMeasure13"] => string(1) " "
      ["strMeasure14"] => string(1) " "
      ["strMeasure15"] => string(1) " "
      ["strMeasure16"] => string(1) " "
      ["strMeasure17"] => string(1) " "
      ["strMeasure18"] => string(1) " "
      ["strMeasure19"] => string(1) " "
      ["strMeasure20"] => string(1) " "
      ["strSource"] => string(68) "http://allrecipes.co.uk/recipe/3096/tunisian-tuna-and-egg-briks.aspx"
      ["strImageSource"] => NULL
      ["strCreativeCommonsConfirmed"] => NULL
      ["dateModified"] => NULL
    }
  }
}